### ISSUE TITLE
Mac OS 10.15 (19A583) Unable to start

### ISSUE THREAD

**Issue by imlinchun** [mongodb/homebrew-brew#22] opened 2019-10-10 12:34 UTC
$ mongo
MongoDB shell version v4.2.0
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
2019-10-10T20:31:42.918+0800 E  QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2019-10-10T20:31:42.923+0800 F  -        [main] exception: connect failed
2019-10-10T20:31:42.923+0800 E  -        [main] exiting with code 1

**Comment by theyeshu** [comment] 2019-10-11 02:10
Same issue

**Comment by imlinchun** [comment] 2019-10-11 10:05
**Solved the problem with the following command**
`mongod --dbpath /usr/local/var/`

Refer to the link below
[https://stackoverflow.com/questions/58283257/mongodb-doesnt-work-on-latest-mac-os10-15](url)

<img width="761" alt="a001" src="https://user-images.githubusercontent.com/43442823/66643595-a2d6c100-ec51-11e9-9727-8f7e6dc37266.png">

**Comment by chasinglogic** [comment] 2019-10-12 14:28
I'm closing this as the problem is not related to the Homebrew packaging. Using the shipped config file should work which does not point at `/data/db` we cannot create this directory in the Homebrew packaging as that would require root and Homebrew should not run as root.

**Closed by chasinglogic** 2019-10-12 14:28 UTC
